<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Two-Factor Enrollment</title>
    @vite([
        'app/Modules/Authentication/assets/css/gov-auth.css',
        'app/Modules/Authentication/assets/js/gov-auth.js',
    ])
</head>
<body class="gov-auth-page">
    <div class="gov-auth-bg" aria-hidden="true"></div>
    <div class="gov-auth-tint" aria-hidden="true"></div>
    <div class="gov-auth-vignette" aria-hidden="true"></div>
    <div class="scanline-overlay" aria-hidden="true"></div>

    <main class="gov-auth-shell">
        <section class="gov-auth-panel" aria-labelledby="portal-heading">
            <header class="auth-header">
                <img
                    class="auth-logo"
                    src="{{ Vite::asset('app/Modules/Authentication/assets/Oneportal_logo-removebg-preview.png') }}"
                    alt="OnePortal emblem"
                >
                <p class="auth-kicker">Municipality of Santa Cruz, Laguna</p>
                <h1 id="portal-heading" class="auth-title">Two-Factor Enrollment</h1>
                <p class="auth-subtitle">Santa Cruz, Laguna - Integrated Government Services</p>
            </header>

            <p class="inline-note">Two-factor authentication is required for all administrators. Complete the setup steps below.</p>

            <section class="auth-section">
                <h2>Setup Instructions</h2>
                <ol class="auth-list">
                    <li>Install an authenticator application on your mobile device.</li>
                    <li>Scan the QR code shown below.</li>
                    <li>Enter the 6-digit code generated by your application.</li>
                    <li>Store your recovery codes securely after enrollment.</li>
                </ol>
            </section>

            <section class="auth-section">
                <h2>QR Code</h2>
                <div class="qr-wrap">{!! $QRCode !!}</div>
            </section>

            <section class="auth-section">
                <h2>Manual Setup Key</h2>
                <p class="secret-key"><code>{{ $secretKey }}</code></p>
            </section>

            @if ($errors->any())
                <p class="auth-alert error">{{ $errors->first() }}</p>
            @endif

            <form class="auth-form" method="POST" action="{{ route('two-factor.confirm') }}">
                @csrf

                <div class="auth-form-row">
                    <label for="code">OTP Code</label>
                    <div class="field-wrap">
                        <input
                            class="auth-input"
                            type="text"
                            id="code"
                            name="code"
                            value="{{ old('code') }}"
                            inputmode="numeric"
                            pattern="[0-9]{6}"
                            minlength="6"
                            maxlength="6"
                            required
                            autocomplete="one-time-code"
                            placeholder="000000"
                        >
                    </div>
                </div>

                <div class="auth-actions">
                    <button class="auth-button" type="submit">Confirm and Enable 2FA</button>
                </div>

                <div class="auth-links">
                    <a class="auth-link" href="{{ route('dashboard') }}">Back to dashboard</a>
                </div>
            </form>
        </section>
    </main>

    <footer class="gov-auth-warning">
        You are accessing an official information system of the Municipality of Santa Cruz, Laguna.
        Unauthorized access is prohibited. All activities are monitored and logged.
        Use of this system constitutes consent to monitoring and auditing.
    </footer>
</body>
</html>
