@extends('layouts.auth')

@section('title', 'OnePortal Admin — Two-Factor Setup')

@section('card-wrap-class', 'mw-500')

@section('content')
    <div class="login-card-header">
        <div class="fp-icon-wrap mb-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" viewBox="0 0 16 16">
                <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8m4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5"/>
                <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
            </svg>
        </div>
        <h2 class="login-heading">Two-Factor Setup</h2>
        <p class="login-subheading">Two-factor authentication is required for all administrators.</p>
    </div>

    <ol class="setup-steps mb-4">
        <li>Install an authenticator app on your mobile device.</li>
        <li>Scan the QR code below with the app.</li>
        <li>Enter the 6-digit code generated by the app.</li>
        <li>Store your recovery codes securely after setup.</li>
    </ol>

    <div class="qr-code-wrap mb-3">{!! $QRCode !!}</div>

    <div class="login-field-group">
        <label class="login-label">Manual Setup Key</label>
        <code class="secret-key-display">{{ $secretKey }}</code>
    </div>

    @if ($errors->any())
        <div class="login-alert login-alert--danger" role="alert">{{ $errors->first() }}</div>
    @endif

    <form method="POST" action="{{ route('two-factor.confirm') }}" novalidate>
        @csrf
        <div class="login-field-group">
            <label class="login-label" for="code">OTP Code</label>
            <div class="login-input-wrap">
                <span class="login-input-icon" aria-hidden="true">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8m4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5"/>
                        <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                    </svg>
                </span>
                <input type="text" id="code" name="code" class="login-input"
                    value="{{ old('code') }}" inputmode="numeric" pattern="[0-9]{6}"
                    minlength="6" maxlength="6" placeholder="000000"
                    required autocomplete="one-time-code">
            </div>
        </div>
        <button type="submit" class="login-btn mb-3">Confirm and Enable 2FA</button>
        <p class="text-center mb-0" style="font-size:0.85rem;color:#6b7a99;">
            <a href="{{ route('dashboard') }}" class="login-forgot">Back to Dashboard</a>
        </p>
    </form>
@endsection
