@extends('homepage::layout')

@section('title', 'FAQs - SK OnePortal Kabataan')

@section('content')
<main class="faq-page">
    <section class="faq-hero kabataan-shell" aria-labelledby="faqHeading">
        <div class="faq-hero-copy">
            <span class="faq-eyebrow">Help Center</span>
            <h1 id="faqHeading">Frequently Asked Questions</h1>
            <p>Find quick answers about the Kabataan platform, youth programs, participation rules, and data privacy.</p>
        </div>

        <div class="faq-hero-search">
            <label for="faqSearch" class="sr-only">Search FAQs</label>
            <div class="faq-search-control">
                <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
                    <circle cx="11" cy="11" r="8" stroke="currentColor" stroke-width="2"/>
                    <path d="m21 21-4.35-4.35" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                </svg>
                <input id="faqSearch" type="search" placeholder="Search by question, keyword, or topic" aria-label="Search frequently asked questions"/>
            </div>
            <p class="faq-hint">Try: registration, programs, privacy, login</p>
        </div>
    </section>

    <section class="faq-layout kabataan-shell" aria-label="FAQ content">
        <section class="faq-content">
            <div id="faqList" role="region" aria-label="FAQ items"></div>
        </section>
    </section>
</main>
@endsection

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const faqList = document.getElementById('faqList');
        const faqSearch = document.getElementById('faqSearch');
        const fallbackFaqs = [
            {
                question: 'What youth programs can I apply for in SK OnePortal?',
                answer: 'You can apply to common SK programs such as scholarship support, sports leagues, health and wellness activities, and livelihood trainings, depending on what your barangay posts.'
            },
            {
                question: 'How will I know if my program application is approved?',
                answer: 'After submitting an application, your dashboard will show the latest status. You will also receive updates through your registered account notifications and email.'
            },
            {
                question: 'Can I join programs outside my barangay?',
                answer: 'Some programs allow cross-barangay participation. Check each listing for eligibility rules, age requirements, and available slots before applying.'
            },
            {
                question: 'What documents are usually needed for scholarship programs?',
                answer: 'Most scholarship listings request basic profile details, school information, and supporting documents such as proof of enrollment. Exact requirements are shown in the program details.'
            },
            {
                question: 'What happens if a program reaches its participant limit?',
                answer: 'When all slots are filled, the program status is updated and new submissions may close automatically. You can still monitor for reopenings or similar upcoming programs.'
            }
        ];

        const sourceFaqs = @json($faqs ?? []);
        const programFaqs = Array.isArray(sourceFaqs)
            ? sourceFaqs.filter(item => item && item.category === 'programs').map(item => ({
                question: item.question,
                answer: item.answer
            }))
            : [];
        const faqsToRender = programFaqs.length ? programFaqs : fallbackFaqs;

        function renderFaqs(query) {
            const normalizedQuery = (query || '').trim().toLowerCase();
            const filteredFaqs = faqsToRender.filter((item) => {
                const question = (item.question || '').toLowerCase();
                const answer = (item.answer || '').toLowerCase();
                return !normalizedQuery || question.includes(normalizedQuery) || answer.includes(normalizedQuery);
            });

            faqList.innerHTML = '';

            if (!filteredFaqs.length) {
                faqList.innerHTML = '<article><button class="faq-toggle" type="button" aria-expanded="false"><span>No results found</span></button><div class="faq-answer"><div class="faq-answer-content">Try searching for terms like program, scholarship, sports, or application.</div></div></article>';
                return;
            }

            filteredFaqs.forEach((item, index) => {
                const article = document.createElement('article');
                const answerId = 'faq-answer-' + index;
                const autoGeneratedAnswer = item.answer + ' This answer is auto-generated from current program guidelines.';
                article.innerHTML = `
                    <button class="faq-toggle" type="button" aria-expanded="false" aria-controls="${answerId}">
                        <span>${item.question}</span>
                        <span class="toggle-icon" aria-hidden="true">
                            <svg class="chevron" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.51a.75.75 0 01-1.08 0l-4.25-4.51a.75.75 0 01.02-1.06z" clip-rule="evenodd"/>
                            </svg>
                        </span>
                    </button>
                    <div class="faq-answer" id="${answerId}" hidden>
                        <div class="faq-answer-content">${autoGeneratedAnswer}</div>
                    </div>
                `;

                const toggle = article.querySelector('.faq-toggle');
                const answer = article.querySelector('.faq-answer');

                toggle.addEventListener('click', function () {
                    const expanded = toggle.getAttribute('aria-expanded') === 'true';
                    toggle.setAttribute('aria-expanded', expanded ? 'false' : 'true');
                    if (expanded) {
                        answer.setAttribute('hidden', '');
                    } else {
                        answer.removeAttribute('hidden');
                    }
                });

                faqList.appendChild(article);
            });
        }

        renderFaqs('');
        faqSearch.addEventListener('input', function () {
            renderFaqs(faqSearch.value);
        });
    });
</script>
@endpush
